config/routes.rb
Rumsfeld::Application.routes.draw do
  root to: "static_pages#home"
  
  resources :letters
  resources :users
  resources :requests do
    resources :statuses
  end
  resources :request_types
  resources :sessions, only: [:new, :create, :destroy]
  
  match '/help',      to: "static_pages#help"
  match '/about',     to: "static_pages#about"
  match '/contact',   to: "static_pages#contact"
  match '/signup',    to: "users#new"
  match '/signin',    to: 'sessions#new'
  match '/signout',   to: 'sessions#destroy'
  match '/print/:id', to: 'print_letters#show', as: 'print'

  match '/requests/:id/editletter', to: 'requests#edit_letter', as: "request_editletter", via: "get"

end

app/controllers/request_types_controller.rb
class RequestTypesController < ApplicationController
  # GET /request_types
  # GET /request_types.json
  def index
    @request_types = RequestType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @request_types }
    end
  end

  # GET /request_types/1
  # GET /request_types/1.json
  def show
    @request_type = RequestType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @request_type }
    end
  end

  # GET /request_types/new
  # GET /request_types/new.json
  def new
    @request_type = RequestType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @request_type }
    end
  end

  # GET /request_types/1/edit
  def edit
    @request_type = RequestType.find(params[:id])
  end

  # POST /request_types
  # POST /request_types.json
  def create
    @request_type = RequestType.new(params[:request_type])

    respond_to do |format|
      if @request_type.save
        format.html { redirect_to @request_type, notice: 'Request type was successfully created.' }
        format.json { render json: @request_type, status: :created, location: @request_type }
      else
        format.html { render action: "new" }
        format.json { render json: @request_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /request_types/1
  # PUT /request_types/1.json
  def update
    @request_type = RequestType.find(params[:id])

    respond_to do |format|
      if @request_type.update_attributes(params[:request_type])
        format.html { redirect_to @request_type, notice: 'Request type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @request_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /request_types/1
  # DELETE /request_types/1.json
  def destroy
    @request_type = RequestType.find(params[:id])
    @request_type.destroy

    respond_to do |format|
      format.html { redirect_to request_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/request_types_helper.rb
module RequestTypesHelper
end

app/views/request_types/_form.html.erb
<%= form_for(@request_type) do |f| %>
  <% if @request_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request_type.errors.count, "error") %> prohibited this request_type from being saved:</h2>

      <ul>
      <% @request_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :template %><br />
    <%= f.text_area :template %>
  </div>
  <div class="actions">
    <%= f.submit "Save Template" %>
  </div>
<% end %>

app/views/request_types/edit.html.erb
<% provide(:title, "Edit templates") %>
<h1>Editing template</h1>

<%= render 'form' %>

<%= link_to 'Show', @request_type %> |
<%= link_to 'Back', request_types_path %>

app/views/request_types/index.html.erb
<% provide(:title, "Letter templates") %>
<div class="row-fluid">
  <h1>Letter templates</h1>

  <p>
    <%= link_to 'New template', new_request_type_path, class: "btn btn-primary active" %>
  </p>
</div>

<div class="row-fluid">
  <table class="table table-condensed">
  <% @request_types.each do |request_type| %>
    <tr>
      <td>
        <strong><%= request_type.name %></strong>
        <%= link_to 'Edit', edit_request_type_path(request_type), class: "btn btn-mini"%>
        <%= link_to 'Show', request_type_path(request_type), class: "btn btn-mini"%>
        <%= link_to 'Destroy', request_type, confirm: 'Are you sure?', method: :delete, class: "btn btn-mini" %>
      </td>
    </tr>
    <tr>
      <td><%= sanitize(RedCloth.new(request_type.template).to_html) %></td>
    </tr>
    <tr><td></td></tr>
  <% end %>
  </table>
</div>

app/views/request_types/new.html.erb
<% provide(:title, "New template") %>
<div class="row-fluid">
  <h1>New template</h1>

  <%= form_for(@request_type) do |f| %>
    <% if @request_type.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@request_type.errors.count, "error") %> prohibited this request_type from being saved:</h2>

        <ul>
        <% @request_type.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :template %><br />
      <%= f.text_area :template, value: RequestType.find_by_name('Generic').template %>
    </div>
    <div class="actions">
      <%= f.submit "Save Template" %>
    </div>
  <% end %>

  <%= link_to 'Back', request_types_path %>
</div>

app/views/request_types/show.html.erb
<% provide(:title, "#{@request_type.name} template") %>
<div class="row-fluid">
	<p id="notice"><%= notice %></p>

	<h1><%= @request_type.name %> Template</h1>

	<p>
	<%= link_to 'Edit', edit_request_type_path(@request_type), class: "btn btn-primary btn-mini active" %>
	</p>

	<p>
	  <%= sanitize(RedCloth.new(@request_type.template).to_html) %>
	</p>
</div>