config/routes.rb
Rumsfeld::Application.routes.draw do
  root to: "static_pages#home"
  
  resources :letters
  resources :users
  resources :requests do
    resources :statuses
  end
  resources :request_types
  resources :sessions, only: [:new, :create, :destroy]
  
  match '/help',      to: "static_pages#help"
  match '/about',     to: "static_pages#about"
  match '/contact',   to: "static_pages#contact"
  match '/signup',    to: "users#new"
  match '/signin',    to: 'sessions#new'
  match '/signout',   to: 'sessions#destroy'
  match '/print/:id', to: 'print_letters#show', as: 'print'

  match '/requests/:id/editletter', to: 'requests#edit_letter', as: "request_editletter", via: "get"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer         not null, primary key
#  name            :string(255)
#  email           :string(255)
#  phone           :string(255)
#  title           :string(255)
#  organization    :string(255)
#  address         :string(255)
#  city            :string(255)
#  state           :string(255)
#  zip             :string(255)
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#  password_digest :string(255)
#

class User < ActiveRecord::Base
	has_many :requests, dependent: :destroy
	has_secure_password
	attr_accessible :name, :email, :phone, :title, :organization, :address,
	                :city, :state, :zip, :password, :password_confirmation

	liquid_methods :name, :email, :phone, :title, :organization, :address,
                 :city, :state, :zip
  
	before_save { |user| user.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_REGEX }
	validates :name, presence: true
	validates :password, length: { minimum: 6 }
	validates :password_confirmation, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize,    only: [:index, :show, :edit, :update]
  before_filter :correct_user, only: [:show, :edit, :update]
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @requests = @user.requests

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'Profile updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :organization %><br />
    <%= f.text_field :organization %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<h1>Update your profile</h1>

<div class="row-fluid">
  <div class="span6 offset3">
    <p>
      <strong>Please enter information as you wish it to appear in your records request letters:</strong>
    </p>
  <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :phone %>
      <%= f.text_field :phone %>

      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :organization %>
      <%= f.text_field :organization %>

      <%= f.label :address %>
      <%= f.text_field :address %>

      <%= f.label :city %>
      <%= f.text_field :city %>

      <%= f.label :state %>
      <%= f.text_field :state %>

      <%= f.label :zip %>
      <%= f.text_field :zip %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="row-fluid">
    <h1>Listing users</h1>

    <table>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Title</th>
        <th>Organization</th>
        <th>Address</th>
        <th>City</th>
        <th>State</th>
        <th>Zip</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= user.title %></td>
        <td><%= user.organization %></td>
        <td><%= user.address %></td>
        <td><%= user.city %></td>
        <td><%= user.state %></td>
        <td><%= user.zip %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
      </tr>
    <% end %>
    </table>

    <br />

    <%= link_to 'New User', new_user_path %>
</div>

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <p>
      <strong>Please enter information as you wish it to appear in your records request letters:</strong>
    </p>
    <%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :phone %>
      <%= f.text_field :phone %>

      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :organization %>
      <%= f.text_field :organization %>

      <%= f.label :address %>
      <%= f.text_field :address %>

      <%= f.label :city %>
      <%= f.text_field :city %>

      <%= f.label :state %>
      <%= f.text_field :state %>

      <%= f.label :zip %>
      <%= f.text_field :zip %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>

<div class="row">
  <div class="span2">
    <p><%= @user.requests.count %> requests:</p>
    <p><%= @user.requests.unsent.count %> unsent</p>
    <p><%= @user.requests.sent.count %> awaiting response</p>
    <p><%= @user.requests.responses_late.count %> past three-day limit<p>
  </div>

  <div class="span10">
    <p><%= link_to "New Request", new_request_path, class: "btn btn-mini btn-primary active" %></p>
    <table class="table table-condensed">
	    <% if @user.requests.any? %>
        <%= render @user.requests %>
      <% end %>
    </table>
  </div>
</div>