config/routes.rb
Rumsfeld::Application.routes.draw do
  root to: "static_pages#home"
  
  resources :letters
  resources :users
  resources :requests do
    resources :statuses
  end
  resources :request_types
  resources :sessions, only: [:new, :create, :destroy]
  
  match '/help',      to: "static_pages#help"
  match '/about',     to: "static_pages#about"
  match '/contact',   to: "static_pages#contact"
  match '/signup',    to: "users#new"
  match '/signin',    to: 'sessions#new'
  match '/signout',   to: 'sessions#destroy'
  match '/print/:id', to: 'print_letters#show', as: 'print'

  match '/requests/:id/editletter', to: 'requests#edit_letter', as: "request_editletter", via: "get"

end

app/models/request.rb
# == Schema Information
#
# Table name: requests
#
#  id                     :integer         not null, primary key
#  recipient_name         :string(255)
#  recipient_title        :string(255)
#  recipient_organization :string(255)
#  recipient_addr         :string(255)
#  recipient_city         :string(255)
#  recipient_state        :string(255)
#  recipient_zip          :string(255)
#  request_text           :text
#  user_id                :integer
#  request_type_id        :integer
#  created_at             :datetime        not null
#  updated_at             :datetime        not null
#  letter                 :text
#

class Request < ActiveRecord::Base
  before_create :generate_letter
  after_create  :status_pending

	belongs_to :user
	belongs_to :request_type
  has_many :statuses
  attr_accessible :recipient_addr, :recipient_city, :recipient_name,
                  :recipient_organization, :recipient_state,
                  :recipient_title, :request_type_id, :recipient_zip,
                  :request_text, :letter
                  
  liquid_methods :recipient_name, :recipient_title, :recipient_organization,
                 :recipient_addr, :recipient_city, :recipient_state,
                 :recipient_zip, :request_text, :created_at, :user_name,
                 :user_email, :user_phone, :user_title, :user_organization,
                 :user_address, :user_city, :user_state, :user_zip

  validates :user_id,         presence: true
  validates :recipient_name,  presence: true
  validates :recipient_addr,  presence: true
  validates :recipient_city,  presence: true
  validates :recipient_state, presence: true, length: { maximum: 2, minimum: 2 }
  validates :recipient_zip,   presence: true
  validates :request_type_id, presence: true
  default_scope order: 'requests.created_at DESC'

  delegate :template, to: :request_type
  delegate :name, :email, :phone, :title, :organization,
           :address, :city, :state, :zip,
           to: :user, prefix: true
  
  def self.unsent
    all.select {|r| r.current_status.status == 'pending'}
  end

  def self.sent
    all.select {|r| r.current_status.status == 'sent'}
  end

  def self.responses_due
    all.select {|r| r.response_due?}
  end

  def self.responses_late
    all.select {|r| r.is_in_violation?}
  end
  def generate_letter
    self.letter =  Liquid::Template.parse(template).render('request' => self)
  end

  def current_status
    statuses.first
  end

  def is_in_violation?
    current_status.status == 'sent' &&
      4.business_days.after(current_status.created_at.to_date).past?
  end

  def sent?
    statuses.where("status_events.status_name = 'sent'").joins(:status_event).count == 1
  end

  def response_due?
    current_status.status == 'sent' &&
      3.business_days.after(current_status.created_at.to_date).today?
  end

  def response_received?
    statuses.where("status_events.status_name = 'response received'").joins(:status_event).count == 1
  end

  protected

    def status_pending
      statuses.create( status_event_id: 1 )
      self.letter =  Liquid::Template.parse(template).render('request' => self)
      self.save
    end
end

app/models/request_type.rb
# == Schema Information
#
# Table name: request_types
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  template   :text
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class RequestType < ActiveRecord::Base
	has_many :requests
	attr_accessible :name, :template

	validates :name,     presence: true
	validates :template, presence: true
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_filter :authorize
  
  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @requests }
    end
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
    @request = Request.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @request }
    end
  end

  # GET /requests/new
  # GET /requests/new.json
  def new
    @request = Request.new
    @user = current_user

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @request }
    end
  end

  # GET /requests/1/edit
  def edit
    @user = current_user
    @request = @user.requests.find(params[:id])
  end

  # POST /requests
  # POST /requests.json
  def create
    @user = current_user
    @request = @user.requests.new(params[:request])

    respond_to do |format|
      if @request.save
        format.html { redirect_to @user, notice: 'Request was successfully created.' }
        format.json { render json: @request, status: :created, location: @request }
      else
        format.html { render action: "new" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /requests/1
  # PUT /requests/1.json
  def update
    @user = current_user
    @request = @user.requests.find(params[:id])

    respond_to do |format|
      if @request.update_attributes(params[:request])
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @user = current_user
    @request = @user.requests.find(params[:id])
    @request.destroy

    respond_to do |format|
      format.html { redirect_to requests_url }
      format.json { head :no_content }
    end
  end
  
  def edit_letter
    @user = current_user
    @request = @user.requests.find(params[:id])
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/_request.html.erb
<tr class=<%= request.is_in_violation? ? 'violation' : nil %> >
  <% if params[:controller] != 'users' %>
    <td><%= request.user.name %></td>
  <% end %>
  <td><%= link_to request.current_status.status, new_request_status_path(request), title: "Click to update status" %></td>
  <td><%= request.current_status.created_at.strftime("%B %d, %Y") %></td>
  <td><%= request.recipient_organization %></td>
  <td><%= truncate(request.request_text, length: 50) %></td>
  <td>
    <div class="btn-group">
      <%= link_to 'Show', request_path(request), class: "btn btn-mini"%>
      <% if session[:user_id] == request.user_id %>
        <%= link_to 'Edit', edit_request_path(request), class: "btn btn-mini"%></td>
      <% end %>
    </div>
</tr>

app/views/requests/edit.html.erb
<%= provide(:title, "Editing request") %>
<h1>Editing request</h1>
<div class="row">
  <div class="span6 offset3">
    <p>
      <strong>Please enter information as you wish it to appear in your records request letters:</strong>
    </p>
    <%= form_for(@request) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :recipient_name %>
      <%= f.text_field :recipient_name %>

      <%= f.label :recipient_title %>
      <%= f.text_field :recipient_title %>

      <%= f.label :recipient_organization %>
      <%= f.text_field :recipient_organization %>

      <%= f.label :recipient_addr %>
      <%= f.text_field :recipient_addr %>

      <%= f.label :recipient_city %>
      <%= f.text_field :recipient_city %>

      <%= f.label :recipient_state %>
      <%= f.text_field :recipient_state %>

      <%= f.label :recipient_zip %>
      <%= f.text_field :recipient_zip %>

      <%= f.label :request_type_id %>
      <%= f.collection_select :request_type_id, RequestType.all, :id, :name %>

      <%= f.label :request_text, "Description of records you are requesting" %>
      <%= f.text_area :request_text, class: "input-small", style: "width: 465px", rows: "5" %>
      <div class="form-action">
	      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
	      <%= link_to "Cancel", user_path(@user), class: "btn btn-large btn-primary active" %>
	    </div>
    <% end %>
  </div>
</div>

app/views/requests/edit_letter.html.erb
<%= provide(:title, "Editing letter") %>
<h1>Editing letter</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@request) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

      <%= f.hidden_field :recipient_name %>
      <%= f.hidden_field :recipient_title %>
      <%= f.hidden_field :recipient_organization %>
      <%= f.hidden_field :recipient_addr %>
      <%= f.hidden_field :recipient_city %>
      <%= f.hidden_field :recipient_state %>
      <%= f.hidden_field :recipient_zip %>
      <%= f.hidden_field :request_type_id %>
      <%= f.hidden_field :request_text %>

      <%= f.label :letter %>
      <%= f.text_area :letter %>

      <div class="form-action">
	      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
	    </div>
    <% end %>
  </div>
</div>

app/views/requests/index.html.erb
<%= provide(:title, "Requests") %>
<h1>Requests</h1>

<p>
	<%= link_to 'New Request', new_request_path, class: "btn btn-small btn-primary active" %>
</p>
<table width="80%" class="table table-condensed">
	<%= render @requests %>
</table>

<br />

app/views/requests/new.html.erb
<%= provide(:title, "New request") %>
<h1>New request</h1>
<div class="row">
  <div class="span6 offset3">
    <p>
      <strong>Please enter information as you wish it to appear in your records request letters:</strong>
    </p>
    <%= form_for(@request) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :recipient_name %>
      <%= f.text_field :recipient_name %>

      <%= f.label :recipient_title %>
      <%= f.text_field :recipient_title %>

      <%= f.label :recipient_organization %>
      <%= f.text_field :recipient_organization %>

      <%= f.label :recipient_addr %>
      <%= f.text_field :recipient_addr %>

      <%= f.label :recipient_city %>
      <%= f.text_field :recipient_city %>

      <%= f.label :recipient_state %>
      <%= f.text_field :recipient_state %>

      <%= f.label :recipient_zip %>
      <%= f.text_field :recipient_zip %>

      <%= f.label :request_type_id %>
      <%= f.collection_select :request_type_id, RequestType.all, :id, :name %>

      <%= f.label :request_text, "Description of records you are requesting" %>
      <%= f.text_area :request_text, class: "input-small", style: "width: 465px", rows: "5" %>
      <div class="form-action">
	      <%= f.submit "Create new request", class: "btn btn-large btn-primary" %>
	    </div>
    <% end %>
  </div>
</div>

app/views/requests/show.html.erb
<% provide(:title, "Request") %>
<div class="row-fluid">
	<div class="span4">
		<% if @request.user == current_user %>
			<p><%= link_to 'Edit', edit_request_path(@request), class: "btn btn-mini" %></p>
		<% end %>

		<p><b>Requested by:</b> <%= @request.user.name %>, <%= @request.user.organization %></p>
		<p>
			<b>Requested sent to:</b>
			<%= @request.recipient_name %>,
			<%= @request.recipient_title %>,
			<%= @request.recipient_organization %>
		</p>
		<p>
			<b>Address:</b>
			<%= @request.recipient_addr %>,
			<%= @request.recipient_city %>,
			<%= @request.recipient_state %>
			<%= @request.recipient_zip %>
		</p>
		<p>
			<b>Request type:</b> <%= @request.request_type.name %>
		<p>
			<b>Request description:</b><br/>
			<%= sanitize(RedCloth.new(@request.request_text).to_html) %>
		</p>
	</div>

	<div class="span7 offset1">
		<p>
			<%= link_to "Update status", new_request_status_path(@request), class: "btn btn-mini" %>
		</p>
		<p>
			<strong>Current status:</strong> <%= @request.current_status.status %> (<%= @request.current_status.created_at.strftime("%B %d, %Y") %>)
 		</p>
		<p>
			<b>Status History:</b>
		</p>
		<ul>
			<% @request.statuses.each do |status| %>
				<li><%= status.status %> (<%= status.created_at.strftime("%B %d, %Y") %>)</li>
			<% end %>
			</ul>
	</div>
</div>

<div class="row"><hr/></div>

<div class="row">
	<div class="span8 offset1">

		<p>
			<div class="btn-group">
				<% if @request.user == current_user %>
					<%= link_to "Edit letter",  request_editletter_path(@request), class: "btn btn-mini" %>
				<% end %>
				
				<%= link_to "Print letter", print_path(@request), class: "btn btn-mini" %>
				<%= link_to "Download PDF", print_path(@request, format: "pdf"), class: "btn btn-mini" %>
			</div>
		</p>

		<p>
			<%= sanitize(RedCloth.new(@request.letter).to_html) %>
		</p>
	</div>
</div>