config/routes.rb
Rumsfeld::Application.routes.draw do
  root to: "static_pages#home"
  
  resources :letters
  resources :users
  resources :requests do
    resources :statuses
  end
  resources :request_types
  resources :sessions, only: [:new, :create, :destroy]
  
  match '/help',      to: "static_pages#help"
  match '/about',     to: "static_pages#about"
  match '/contact',   to: "static_pages#contact"
  match '/signup',    to: "users#new"
  match '/signin',    to: 'sessions#new'
  match '/signout',   to: 'sessions#destroy'
  match '/print/:id', to: 'print_letters#show', as: 'print'

  match '/requests/:id/editletter', to: 'requests#edit_letter', as: "request_editletter", via: "get"

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="https://github.com/DallasMorningNews/project-rumsfeld">The Rumsfeld Project</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar">
  <div class="navbar-inner">
    <div class="container-fluid">
      <%= link_to "Request Tracker", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if current_user %>
            <li><%= link_to "Home",      user_path(current_user) %></li>
            <li><%= link_to 'Requests',  requests_path %></li>
            <li><%= link_to 'Templates', request_types_path %></li>
        <% else %>
            <li><%= link_to "Home", root_path %></li>
          <% end %>
          <li><%= link_to "Help", help_path %></li>
          <% if current_user %>
            <li><%= link_to "Settings", edit_user_path(current_user) %>
						<li><%= link_to "Sign out", signout_path %>
          <% else %>
          	<li><%= link_to "Sign in", signin_path %></li>
					<% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Rumsfeld | <%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
    <div class="container">
			<% flash.each do |key, value| %>
				<div class="alert alert-<%= key %>"><%= value %></div>
			<% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <% if Rails.env.development? %>
  			<%= debug(params) %>
        <%= debug(session) %>
      <% end %>
    </div>
  </body>

</html>

app/views/layouts/print_letters.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rumsfeld | <%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div class="container">
      <%= yield %>
			<%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>